name: istakip
description: Aksoyhlc order/project tracking application.

#Aksoyhlc sipariş/proje takip uygulaması/programı ile
#müşterilerinizden aldığınız siparişlerin ve başlattığınız projelerin
#kayıtlarını tutabilir ve Web-Masaüstü Programı-Mobil Uygulama üzerinden erişebilirsiniz.
#Bu uygulama ve yazılım ücretsiz olarak kullanıma sunulmuştur,
#lütfen ticari amaçlar için kullanmayın.


#With the Aksoyhlc order/project tracking application/program,
#you can keep the records of the orders you receive from your customers and
#the projects you have initiated and
#access them via the Web-Desktop Program-Mobile Application.
#This application and software is available for free,
#please do not use it for commercial purposes.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev



version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.4
  google_fonts: ^2.3.1
  http: ^0.13.4
  get_storage: ^2.0.3
  auto_size_text: ^3.0.0
  flutter_html: ^2.2.1
  url_launcher: ^6.0.20
  html_unescape: ^2.0.0
  mask_text_input_formatter: ^2.3.0
  html_editor_enhanced: ^2.4.0+1
  file_picker: ^4.5.1
  dio: ^4.0.6
  path_provider: ^2.0.9
  share_plus: ^4.0.3
  convex_bottom_bar: ^3.0.0
  get: ^4.6.1
  dropdown_button2: ^1.2.3
  flutter_launcher_icons: ^0.9.2
  change_app_package_name: ^1.0.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:

  uses-material-design: true

  assets:
    - assets/
    

